FROM wangkaihua/qwen2-nvidia-base:002

RUN pip3 install --no-cache-dir accelerate \
    && pip3 install --no-cache-dir qwen-vl-utils \
    && pip3 install ninja

RUN CUDA_HOME=/usr/local/cuda \ 
    pip3 install --no-cache-dir --no-build-isolation flash-attn==2.6.1

RUN mkdir -p /data/shared/code \
    && cd /data/shared/code \
    && git clone https://github.com/fyabc/vllm.git \
    && cd vllm \
    && git checkout add_qwen2_vl_new \
    && pip3 install --no-cache-dir -r requirements-cuda.txt \
    && pip3 install --no-cache-dir --no-build-isolation . \
    && cd /data/shared/Qwen \
    && rm -rf /data/shared/code/vllm

RUN pip3 install --no-cache-dir \
    gradio==4.42.0 \
    gradio_client==1.3.0 \
    transformers-stream-generator==0.0.4 \
    fastapi uvicorn

COPY ./web_demo_mm.py ./

EXPOSE 80